/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: "doc",
      id: "Getting_Started",
      label: "Getting Started",
      className:'bolder',
    },
    {
      type: "category",
      label: "IoT Gateway Hardware",
      className:'bolder',
      collapsed: false,
      link: {
        type: "doc",
        id: "IoT_Gateway_Hardware",
      },
      items: [
       // ============Smart IoT Gateway===============
        {
          type: "link",
          href: "/Blank",
          label: "Smart IoT Gateway",
          className: "first",
        },
        {
          type: "category",
          label: "DSGW-290 RK3568 Gateway",
          link: {
            type: "doc",
            id: "IoT_Gateway_Hardware/DSGW-290 RK3568 Gateway/Overview",
          },
          items: [
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-290 RK3568 Gateway/Specification",
              label: "Specification",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-290 RK3568 Gateway/User Manual",
              label: "User Manual",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-290 RK3568 Gateway/Quick Start Guide",
              label: "Quick Start Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-290 RK3568 Gateway/GUI Operating Guide",
              label: "GUI Operating Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-290 RK3568 Gateway/FAQs",
              label: "FAQs",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-290 RK3568 Gateway/Release Note",
              label: "Release Note",
            },
          ],
        },
        {
          type: "category",
          label: "DSGW-210 RK3328 Gateway",
          link: {
            type: "doc",
            id: "IoT_Gateway_Hardware/DSGW-210 RK3328 Gateway/Overview",
          },
          items: [
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-210 RK3328 Gateway/Specification",
              label: "Specification",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-210 RK3328 Gateway/User Manual",
              label: "User Manual",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-210 RK3328 Gateway/Quick Start Guide",
              label: "Quick Start Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-210 RK3328 Gateway/GUI Operating Guide",
              label: "GUI Operating Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-210 RK3328 Gateway/FAQs",
              label: "FAQs",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-210 RK3328 Gateway/Release Note",
              label: "Release Note",
            },
          ],
        },
        {
          type: "category",
          label: "DSGW-211 PX30 Gateway",
          link: {
            type: "doc",
            id: "IoT_Gateway_Hardware/DSGW-211 PX30 Gateway/Overview",
          },
          items: [
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-211 PX30 Gateway/Specification",
              label: "Specification",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-211 PX30 Gateway/User Manual",
              label: "User Manual",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-211 PX30 Gateway/Quick Start Guide",
              label: "Quick Start Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-211 PX30 Gateway/GUI Operating Guide",
              label: "GUI Operating Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-211 PX30 Gateway/FAQs",
              label: "FAQs",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-211 PX30 Gateway/Release Note",
              label: "Release Note",
            },
          ],
        },
        {
          type: "category",
          label: "DSGW-230 RK3328 Gateway",
          link: {
            type: "doc",
            id: "IoT_Gateway_Hardware/DSGW-230 RK3328 Gateway/Overview",
          },
          items: [
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-230 RK3328 Gateway/Specification",
              label: "Specification",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-230 RK3328 Gateway/User Manual",
              label: "User Manual",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-230 RK3328 Gateway/Quick Start Guide",
              label: "Quick Start Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-230 RK3328 Gateway/GUI Operating Guide",
              label: "GUI Operating Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-230 RK3328 Gateway/FAQs",
              label: "FAQs",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-230 RK3328 Gateway/Release Note",
              label: "Release Note",
            },
          ],
        },
        {
          type: "category",
          label: "DSGW-120 PX30 Gateway",
          link: {
            type: "doc",
            id: "IoT_Gateway_Hardware/DSGW-120 PX30 Gateway/Overview",
          },
          items: [
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-120 PX30 Gateway/Specification",
              label: "Specification",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-120 PX30 Gateway/User Manual",
              label: "User Manual",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-120 PX30 Gateway/Quick Start Guide",
              label: "Quick Start Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-120 PX30 Gateway/GUI Operating Guide",
              label: "GUI Operating Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-120 PX30 Gateway/FAQs",
              label: "FAQs",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-120 PX30 Gateway/Release Note",
              label: "Release Note",
            },
          ],
        },
        {
          type: "category",
          label: "DSGW-030 MTK7688 Gateway",
          link: {
            type: "doc",
            id: "IoT_Gateway_Hardware/DSGW-030 MTK7688 Gateway/Overview",
          },
          items: [
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-030 MTK7688 Gateway/Specification",
              label: "Specification",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-030 MTK7688 Gateway/User Manual",
              label: "User Manual",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-030 MTK7688 Gateway/Quick Start Guide",
              label: "Quick Start Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-030 MTK7688 Gateway/GUI Operating Guide",
              label: "GUI Operating Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-030 MTK7688 Gateway/FAQs",
              label: "FAQs",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-030 MTK7688 Gateway/Release Note",
              label: "Release Note",
            },
          ],
        },
        {
          type: "category",
          label: "DSGW-090 MTK7628 Gateway",
          link: {
            type: "doc",
            id: "IoT_Gateway_Hardware/DSGW-090 MTK7628 Gateway/Overview",
          },
          items: [
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-090 MTK7628 Gateway/Specification",
              label: "Specification",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-090 MTK7628 Gateway/User Manual",
              label: "User Manual",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-090 MTK7628 Gateway/Quick Start Guide",
              label: "Quick Start Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-090 MTK7628 Gateway/GUI Operating Guide",
              label: "GUI Operating Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-090 MTK7628 Gateway/FAQs",
              label: "FAQs",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-090 MTK7628 Gateway/Release Note",
              label: "Release Note",
            },
          ],
        },
        {
          type: "category",
          label: "DSGW-092 ESP32 Gateway",
          link: {
            type: "doc",
            id: "IoT_Gateway_Hardware/DSGW-092 ESP32 Gateway/Overview",
          },
          items: [
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-092 ESP32 Gateway/Specification",
              label: "Specification",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-092 ESP32 Gateway/User Manual",
              label: "User Manual",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-092 ESP32 Gateway/Quick Start Guide",
              label: "Quick Start Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-092 ESP32 Gateway/GUI Operating Guide",
              label: "GUI Operating Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-092 ESP32 Gateway/FAQs",
              label: "FAQs",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-092 ESP32 Gateway/Release Note",
              label: "Release Note",
            },
          ],
        },
        {
          type: "category",
          label: "DSGW-201 MT7621A Gateway",
          link: {
            type: "doc",
            id: "IoT_Gateway_Hardware/DSGW-201 MT7621A Gateway/Overview",
          },
          items: [
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-201 MT7621A Gateway/Specification",
              label: "Specification",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-201 MT7621A Gateway/User Manual",
              label: "User Manual",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-201 MT7621A Gateway/Quick Start Guide",
              label: "Quick Start Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-201 MT7621A Gateway/GUI Operating Guide",
              label: "GUI Operating Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-201 MT7621A Gateway/FAQs",
              label: "FAQs",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-201 MT7621A Gateway/Release Note",
              label: "Release Note",
            },
          ],
        },
        // ============Industrial IoT Gateway===============
        {
          type: "link",
          href: "/Blank",
          label: "Industrial IoT Gateway",
          className: "first",
        },
        {
          type: "category",
          label: "DSGW-081 i.MX6 ULL Gateway",
          link: {
            type: "doc",
            id: "IoT_Gateway_Hardware/DSGW-081 i.MX6 ULL Gateway/Overview",
          },
          items: [
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-081 i.MX6 ULL Gateway/Specification",
              label: "Specification",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-081 i.MX6 ULL Gateway/User Manual",
              label: "User Manual",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-081 i.MX6 ULL Gateway/Quick Start Guide",
              label: "Quick Start Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-081 i.MX6 ULL Gateway/GUI Operating Guide",
              label: "GUI Operating Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-081 i.MX6 ULL Gateway/FAQs",
              label: "FAQs",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-081 i.MX6 ULL Gateway/Release Note",
              label: "Release Note",
            },
          ],
        },
        {
          type: "category",
          label: "DSGW-006 MT7628AN Gateway",
          link: {
            type: "doc",
            id: "IoT_Gateway_Hardware/DSGW-006 MT7628AN Gateway/Overview",
          },
          items: [
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-006 MT7628AN Gateway/Specification",
              label: "Specification",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-006 MT7628AN Gateway/User Manual",
              label: "User Manual",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-006 MT7628AN Gateway/Quick Start Guide",
              label: "Quick Start Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-006 MT7628AN Gateway/GUI Operating Guide",
              label: "GUI Operating Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-006 MT7628AN Gateway/FAQs",
              label: "FAQs",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-006 MT7628AN Gateway/Release Note",
              label: "Release Note",
            },
          ],
        },
        {
          type: "category",
          label: "DSGW-014 PX30K Gateway",
          link: {
            type: "doc",
            id: "IoT_Gateway_Hardware/DSGW-014 PX30K Gateway/Overview",
          },
          items: [
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-014 PX30K Gateway/Specification",
              label: "Specification",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-014 PX30K Gateway/User Manual",
              label: "User Manual",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-014 PX30K Gateway/Quick Start Guide",
              label: "Quick Start Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-014 PX30K Gateway/GUI Operating Guide",
              label: "GUI Operating Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-014 PX30K Gateway/FAQs",
              label: "FAQs",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-014 PX30K Gateway/Release Note",
              label: "Release Note",
            },
          ],
        },
        {
          type: "category",
          label: "DSGW-380 RK3588 Gateway",
          link: {
            type: "doc",
            id: "IoT_Gateway_Hardware/DSGW-380 RK3588 Gateway/Overview",
          },
          items: [
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-380 RK3588 Gateway/Specification",
              label: "Specification",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-380 RK3588 Gateway/User Manual",
              label: "User Manual",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-380 RK3588 Gateway/Quick Start Guide",
              label: "Quick Start Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-380 RK3588 Gateway/GUI Operating Guide",
              label: "GUI Operating Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-380 RK3588 Gateway/FAQs",
              label: "FAQs",
            },
            {
              type: "doc",
              id: "IoT_Gateway_Hardware/DSGW-380 RK3588 Gateway/Release Note",
              label: "Release Note",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "IoT Gateway with Applications",
      className:'bolder',
      link: {
        type: "doc",
        id: "IoT_Gateway_with_Applications",
      },
      items: [
        {
          type: "category",
          label: "DSGW-210 RK3328 Home Assistant Gateway",
          link: {
            type: "doc",
            id: "IoT_Gateway_with_Applications/DSGW-210 RK3328 Home Assistant Gateway/Overview",
          },
          items: [
            {
              type: "doc",
              id: "IoT_Gateway_with_Applications/DSGW-210 RK3328 Home Assistant Gateway/Specification",
              label: "Specification",
            },
            {
              type: "doc",
              id: "IoT_Gateway_with_Applications/DSGW-210 RK3328 Home Assistant Gateway/User Manual",
              label: "User Manual",
            },
            {
              type: "doc",
              id: "IoT_Gateway_with_Applications/DSGW-210 RK3328 Home Assistant Gateway/Quick Start Guide",
              label: "Quick Start Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_with_Applications/DSGW-210 RK3328 Home Assistant Gateway/FAQs",
              label: "FAQs",
            },
            {
              type: "doc",
              id: "IoT_Gateway_with_Applications/DSGW-210 RK3328 Home Assistant Gateway/Release Note",
              label: "Release Note",
            },
          ],
        },
        {
          type: "category",
          label: "DSGW-040 MT7620 Router Gateway",
          link: {
            type: "doc",
            id: "IoT_Gateway_with_Applications/DSGW-040 MT7620 Router Gateway/Overview",
          },
          items: [
            {
              type: "doc",
              id: "IoT_Gateway_with_Applications/DSGW-040 MT7620 Router Gateway/Specification",
              label: "Specification",
            },
            {
              type: "doc",
              id: "IoT_Gateway_with_Applications/DSGW-040 MT7620 Router Gateway/User Manual",
              label: "User Manual",
            },
            {
              type: "doc",
              id: "IoT_Gateway_with_Applications/DSGW-040 MT7620 Router Gateway/Quick Start Guide",
              label: "Quick Start Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_with_Applications/DSGW-040 MT7620 Router Gateway/FAQs",
              label: "FAQs",
            },
            {
              type: "doc",
              id: "IoT_Gateway_with_Applications/DSGW-040 MT7620 Router Gateway/Release Note",
              label: "Release Note",
            },
          ],
        },
        {
          type: "category",
          label: "DSGW-021 MT7628AN Router Gateway",
          link: {
            type: "doc",
            id: "IoT_Gateway_with_Applications/DSGW-021 MT7628AN Router Gateway/Overview",
          },
          items: [
            {
              type: "doc",
              id: "IoT_Gateway_with_Applications/DSGW-021 MT7628AN Router Gateway/Specification",
              label: "Specification",
            },
            {
              type: "doc",
              id: "IoT_Gateway_with_Applications/DSGW-021 MT7628AN Router Gateway/User Manual",
              label: "User Manual",
            },
            {
              type: "doc",
              id: "IoT_Gateway_with_Applications/DSGW-021 MT7628AN Router Gateway/Quick Start Guide",
              label: "Quick Start Guide",
            },
            {
              type: "doc",
              id: "IoT_Gateway_with_Applications/DSGW-021 MT7628AN Router Gateway/FAQs",
              label: "FAQs",
            },
            {
              type: "doc",
              id: "IoT_Gateway_with_Applications/DSGW-021 MT7628AN Router Gateway/Release Note",
              label: "Release Note",
            },
          ],
        },
      ]
    },
    {
      type: "category",
      label: "System on Modules",
      className:'bolder',
      link: {
        type: "doc",
        id: "System_on_Modules",
      },
      items: [
        {
          type: "category",
          label: "PX30 SoM",
          link: {
            type: "doc",
            id: "System_on_Modules/PX30 SoM/Overview",
          },
          items: [
            {
              type: "doc",
              id: "System_on_Modules/PX30 SoM/Specification",
              label: "Specification",
            },
            {
              type: "doc",
              id: "System_on_Modules/PX30 SoM/User Manual",
              label: "User Manual",
            },
            {
              type: "doc",
              id: "System_on_Modules/PX30 SoM/Quick Start Guide",
              label: "Quick Start Guide",
            },
            {
              type: "doc",
              id: "System_on_Modules/PX30 SoM/Hardware Development Guide",
              label: "Hardware Development Guide",
            },
            {
              type: "doc",
              id: "System_on_Modules/PX30 SoM/Chip Guidance",
              label: "Chip Guidance",
            },
            {
              type: "doc",
              id: "System_on_Modules/PX30 SoM/Deployment Guide",
              label: "Deployment Guide",
            },
            {
              type: "doc",
              id: "System_on_Modules/PX30 SoM/FAQs",
              label: "FAQs",
            },
            {
              type: "doc",
              id: "System_on_Modules/PX30 SoM/Release Note",
              label: "Release Note",
            },
          ]
        },
        {
          type: "category",
          label: "RK3328 SoM",
          link: {
            type: "doc",
            id: "System_on_Modules/RK3328 SoM/Overview",
          },
          items: [
            {
              type: "doc",
              id: "System_on_Modules/RK3328 SoM/Specification",
              label: "Specification",
            },
            {
              type: "doc",
              id: "System_on_Modules/RK3328 SoM/User Manual",
              label: "User Manual",
            },
            {
              type: "doc",
              id: "System_on_Modules/RK3328 SoM/Quick Start Guide",
              label: "Quick Start Guide",
            },
            {
              type: "doc",
              id: "System_on_Modules/RK3328 SoM/Hardware Development Guide",
              label: "Hardware Development Guide",
            },
            {
              type: "doc",
              id: "System_on_Modules/RK3328 SoM/Chip Guidance",
              label: "Chip Guidance",
            },
            {
              type: "doc",
              id: "System_on_Modules/RK3328 SoM/Deployment Guide",
              label: "Deployment Guide",
            },
            {
              type: "doc",
              id: "System_on_Modules/RK3328 SoM/FAQs",
              label: "FAQs",
            },
            {
              type: "doc",
              id: "System_on_Modules/RK3328 SoM/Release Note",
              label: "Release Note",
            },
          ]
        },
        {
          type: "category",
          label: "RK3308 SoM",
          link: {
            type: "doc",
            id: "System_on_Modules/RK3308 SoM/Overview",
          },
          items: [
            {
              type: "doc",
              id: "System_on_Modules/RK3308 SoM/Specification",
              label: "Specification",
            },
            {
              type: "doc",
              id: "System_on_Modules/RK3308 SoM/User Manual",
              label: "User Manual",
            },
            {
              type: "doc",
              id: "System_on_Modules/RK3308 SoM/Quick Start Guide",
              label: "Quick Start Guide",
            },
            {
              type: "doc",
              id: "System_on_Modules/RK3308 SoM/Hardware Development Guide",
              label: "Hardware Development Guide",
            },
            {
              type: "doc",
              id: "System_on_Modules/RK3308 SoM/Chip Guidance",
              label: "Chip Guidance",
            },
            {
              type: "doc",
              id: "System_on_Modules/RK3308 SoM/Deployment Guide",
              label: "Deployment Guide",
            },
            {
              type: "doc",
              id: "System_on_Modules/RK3308 SoM/FAQs",
              label: "FAQs",
            },
            {
              type: "doc",
              id: "System_on_Modules/RK3308 SoM/Release Note",
              label: "Release Note",
            },
          ]
        },
        {
          type: "category",
          label: "MT7621 SoM",
          link: {
            type: "doc",
            id: "System_on_Modules/MT7621 SoM/Overview",
          },
          items: [
            {
              type: "doc",
              id: "System_on_Modules/MT7621 SoM/Specification",
              label: "Specification",
            },
            {
              type: "doc",
              id: "System_on_Modules/MT7621 SoM/User Manual",
              label: "User Manual",
            },
            {
              type: "doc",
              id: "System_on_Modules/MT7621 SoM/Quick Start Guide",
              label: "Quick Start Guide",
            },
            {
              type: "doc",
              id: "System_on_Modules/MT7621 SoM/Hardware Development Guide",
              label: "Hardware Development Guide",
            },
            {
              type: "doc",
              id: "System_on_Modules/MT7621 SoM/Chip Guidance",
              label: "Chip Guidance",
            },
            {
              type: "doc",
              id: "System_on_Modules/MT7621 SoM/Deployment Guide",
              label: "Deployment Guide",
            },
            {
              type: "doc",
              id: "System_on_Modules/MT7621 SoM/FAQs",
              label: "FAQs",
            },
            {
              type: "doc",
              id: "System_on_Modules/MT7621 SoM/Release Note",
              label: "Release Note",
            },
          ]
        },
        {
          type: "category",
          label: "MT7628 SoM",
          link: {
            type: "doc",
            id: "System_on_Modules/MT7628 SoM/Overview",
          },
          items: [
            {
              type: "doc",
              id: "System_on_Modules/MT7628 SoM/Specification",
              label: "Specification",
            },
            {
              type: "doc",
              id: "System_on_Modules/MT7628 SoM/User Manual",
              label: "User Manual",
            },
            {
              type: "doc",
              id: "System_on_Modules/MT7628 SoM/Quick Start Guide",
              label: "Quick Start Guide",
            },
            {
              type: "doc",
              id: "System_on_Modules/MT7628 SoM/Hardware Development Guide",
              label: "Hardware Development Guide",
            },
            {
              type: "doc",
              id: "System_on_Modules/MT7628 SoM/Chip Guidance",
              label: "Chip Guidance",
            },
            {
              type: "doc",
              id: "System_on_Modules/MT7628 SoM/Deployment Guide",
              label: "Deployment Guide",
            },
            {
              type: "doc",
              id: "System_on_Modules/MT7628 SoM/FAQs",
              label: "FAQs",
            },
            {
              type: "doc",
              id: "System_on_Modules/MT7628 SoM/Release Note",
              label: "Release Note",
            },
          ]
        },
      ]
    }
  ],
};

module.exports = sidebars;
